Repository DeuxHuitHuit/framework.js-modules, pull requests merged in 2018-12, with the labels that each got.

#192 Kebab cased the default page
  src/pages/default-page.js
Labels: one char fix, wait before merge

#193 Prevent fatal error if response parsing fails
  src/modules/form-dyn.js
Labels: bug

#190 Animation System with Bodymovin
  src/com/animation.js
  src/modules/auto-animation.js
Labels: enhancement, requested changes
