Repository DeuxHuitHuit/framework.js-modules, pull requests merged in 2018-11, with the labels that each got.

#160 Synced and updated jshint config w/ template
  Gruntfile.js
Labels: enhancement

#167 Add form-dyn js code
  src/modules/form-dyn-input-states.js
  src/modules/form-dyn-loading.js
  src/modules/form-dyn-messages.js
  src/modules/form-dyn-reset.js
  src/modules/form-dyn.js
Labels: new, proposal

#175 add auto-copy-on-click
  src/modules/auto-copy-on-click.js
Labels: enhancement, new, requested changes

#182 Replaced concat selectors for cleaner traversing methods
  src/com/flickity.js
Labels: enhancement

#179 Changed document.location to window.location
  src/com/algolia-search.js
  src/com/article-changer-v3.js
  src/com/article-changer.js
  src/modules/alt-language-link-updater.js
  src/modules/auto-merge-qs-value.js
  src/modules/auto-scroll-to-id-on-load.js
  src/modules/auto-share-this.js
  src/modules/auto-sync-state-from-qs.js
  src/modules/canonical-updater.js
  src/modules/page-load-errors.js
  src/modules/page-not-found.js
  src/modules/rating.js
  src/modules/recommendations.js
  src/modules/route-not-found.js
  src/modules/share-this.js
  src/modules/site-scroll-keeper.js
  src/modules/title-updater.js
  src/modules/url-changer.js
Labels: enhancement
