Repository DeuxHuitHuit/framework.js-modules, pull requests merged in 2019-08, with the labels that each got.

#129 2.0 framework update
  Gruntfile.js
  src/com/article-changer-v3.js
  src/com/article-changer.js
  src/com/form.js
  src/com/infinite-scroll.js
  src/modules/user-id.js
  src/utils/keys.js
Labels: bug, enhancement, ready to merge

#275 Add fullscreen methode
  src/com/video.js
Labels: enhancement, ready to merge

#276 Create the fx changeState.update
  src/modules/change-state.js
Labels: enhancement, ready to merge

#277 Use fx change state notification instead of modules notification
  src/modules/auto-3-state-on-scroll.js
Labels: enhancement, ready to merge

#279 AutoChangeStateClick : Use fx change state notification
  src/modules/auto-change-state-click.js
Labels: enhancement, ready to merge

#280 AutoChangeStateHover : Use fx change state notification
  src/modules/auto-change-state-hover.js
Labels: enhancement, ready to merge

#281 AutoSyncStateFromQS : Use fx change state notification
  src/modules/auto-sync-state-from-qs.js
Labels: enhancement, ready to merge

#278 Component Video : Use fx change state notification instead of modules notification
  src/com/video.js
Labels: enhancement, ready to merge

#282 AutoOembed : Use fx change state notification
  src/modules/auto-oembed.js
Labels: enhancement, ready to merge

#283 AutoSlideClick : Use fx change state notification
  src/modules/auto-slide-click.js
Labels: enhancement, ready to merge

#284 linkSelector : Use fx change state notification
  src/modules/link-selector.js
Labels: enhancement, ready to merge

#285 slide: Use fx change state notification
  src/modules/slide.js
Labels: enhancement, ready to merge

#286 autoCopyOnClick: Use fx change state notification
  src/modules/auto-copy-on-click.js
Labels: enhancement, ready to merge

#287 autoModal : Use fx change state notification
  src/modules/auto-modal.js
Labels: enhancement, ready to merge

#288 siteLoaderUse : fx change state notification
  src/modules/site-loader.js
Labels: enhancement, ready to merge

#289 form: Use fx change state notification
  src/com/form.js
Labels: enhancement, ready to merge

#290 formField: Use fx change state notification
  src/com/form-field.js
Labels: enhancement, ready to merge

#272 Remove tracking functions from the $ namespace
  src/com/algolia-search.js
  src/com/checkpoint-event.js
  src/com/form.js
  src/com/replace-state-on-scroll.js
  src/fx/tracking.js
  src/modules/auto-tooltips.js
  src/modules/site-error.js
  src/modules/url-changer.js
Labels: breaking change, proposal, ready to merge
