Repository DeuxHuitHuit/framework.js-modules, pull requests merged in 2019-02, with the labels that each got.

#201 New link selector module
  src/modules/link-selector.js
  src/modules/site-nav-link-selector.js
Labels: enhancement, ready to merge

#217 Fix isFirstFragment condition
  src/pages/default-detail-page.js
Labels: bug, one char fix, ready to merge

#216 Fixed watermark's ajax request cors error
  src/modules/watermark.js
Labels: bug, ready to merge

#212 Make it possible to disable auto-tracked-scroll
  src/com/checkpoint-event.js
  src/modules/auto-tracked-scroll.js
Labels: enhancement, ready to merge

#209 Allow leading +1 in phoneUS validation
  src/com/form-field.js
Labels: bug, ready to merge

#198 Add new form validation rules
  src/com/form-field.js
  src/com/form.js
Labels: enhancement, ready to merge
