Repository DeuxHuitHuit/framework.js-modules, pull requests merged in 2019-01, with the labels that each got.

#204 Use infos for page loader, not warn
  src/modules/page-load.js
Labels: enhancement

#200 fix auto-play
  src/modules/auto-oembed.js
Labels: bug

#202 Changed Bodymovin to Airbnb's Lottie
  src/com/animation.js
  src/modules/auto-animation.js
Labels: enhancement, ready to merge

#208 Remove defaultBeginTransition callback parameter
  src/transitions/default-transition.js
  src/transitions/popup-transition.js
Labels: ready to merge

#203 Watermark module
  src/modules/watermark.js
Labels: enhancement

#197 Autorize embed in mobile when they aren't video.
  src/com/oembed.js
  src/modules/auto-oembed.js
  src/modules/oembed-vm.js
  src/modules/oembed-yt.js
Labels: enhancement, ready to merge

#196 Set two step anim as the default behavior
  src/com/article-changer-v3.js
Labels: enhancement, ready to merge
