Repository DeuxHuitHuit/framework.js-modules, pull requests merged in 2019-12, with the labels that each got.

#194 Add support for list of possible values
  src/modules/auto-sync-state-from-qs.js
Labels: enhancement, needs testing, ready to merge, wait before merge

#298 Removed video resizing
  src/com/video.js
Labels: breaking change, proposal, ready to merge

#325 Fix empty updateQsFragment
  src/modules/url-changer.js
Labels: bug, needs testing, ready to merge

#299 ComputeOptions fx
  src/fx/compute-options.js
Labels: enhancement, proposal, requested changes
