Repository DeuxHuitHuit/framework.js-modules, pull requests merged in 2019-06, with the labels that each got.

#240 Change State: Process a list of elements instead of only one
  src/modules/change-state.js
Labels: enhancement, proposal, ready to merge

#265 Fix line too long for changeState
  src/modules/change-state.js
Labels: ready to merge

#263 Add skew function to css3-generator utils
  src/utils/css3-generator.js
Labels: enhancement, ready to merge

#262 Remove weird extra 0; in the top of the file
  src/utils/css3-generator.js
Labels: ready to merge

#260 Allo customisation of the highlight tags
  src/com/algolia-search.js
Labels: enhancement, ready to merge

#261 Add url history module
  src/modules/history.js
Labels: enhancement

#254 Add an optional pageview upon search
  src/com/algolia-search.js
Labels: enhancement, ready to merge

#253 Do not send a pageview when no fragment change
  src/modules/url-changer.js
Labels: bug, ready to merge

#211 Add auto state on scroll bounds modules
  src/modules/auto-state-on-scroll-bounds.js
Labels: enhancement, ready to merge

#250 Filter Algolia Hits
  src/com/algolia-search.js
Labels: enhancement, ready to merge

#255 Reset all states before setting them
  src/modules/link-selector.js
Labels: bug, ready to merge

#239 Replace popup by modal (now auto-modal)
  src/modules/auto-modal.js
  src/modules/popup.js
Labels: enhancement, ready to merge
