Repository DeuxHuitHuit/framework.js-modules, pull requests merged in 2019-05, with the labels that each got.

#242 Pause all non visible flickity
  src/com/flickity.js
Labels: enhancement, proposal, ready to merge

#251 form-dyn Remove double affectation
  src/modules/form-dyn.js
Labels: enhancement

#235 Fix nextPage null, Dual StartAnim in some case, Add navigateTo Feedback.
  src/com/article-changer-v3.js
Labels: bug, enhancement, proposal, ready to merge

#256 Fix multiple ready event for autoplay video
  src/modules/oembed-vm.js
Labels: bug
