Repository DeuxHuitHuit/framework.js-modules, pull requests merged in 2019-04, with the labels that each got.

#229 Mute oembed players when auto play is enabled
  src/modules/oembed-vm.js
  src/modules/oembed-yt.js
Labels: enhancement, ready to merge

#225 Fixed uninitable flickity
  src/com/flickity.js
Labels: bug

#224 Fix sync property default scope to match documentation
  src/modules/auto-sync-property.js
Labels: bug, ready to merge

#205 Google-map update
  src/com/google-map.js
Labels: enhancement, ready to merge

#231 add check for data
  src/modules/auto-scroll-to-id-on-load.js
Labels: bug, ready to merge

#206 Add auto-tooltips.js module
  src/modules/auto-tooltips.js
Labels: enhancement, ready to merge

#228 Add support for detecting file sizes client side
  Gruntfile.js
  src/com/form-field.js
Labels: enhancement, ready to merge

#230 Port changes to change-state
  src/modules/change-state.js
Labels: bug, enhancement, ready to merge
