Repository DeuxHuitHuit/framework.js-modules, pull requests merged in 2019-07, with the labels that each got.

#269 Use the hash id for ga tracking if no ga-cat
  src/modules/auto-scroll-to-id.js
Labels: enhancement

#246 Accept multiple offset selectors
  src/modules/auto-scroll-to-id.js
Labels: enhancement, ready to merge

#271 Replace non existent function call with new version
  src/modules/links.js
Labels: bug

#238 Cleanup form.js and form-field.js
  src/com/form-field.js
  src/com/form.js
Labels: breaking change, enhancement, proposal, ready to merge

#264 named the endpoint the same as the method
  src/com/animation.js
Labels: breaking change, enhancement, ready to merge

#266 update the namespace of keys for framework2
  src/modules/keyboard-nav.js
Labels: bug, ready to merge

#273 [video.js] Add toggleMute public accessor
  src/com/video.js
Labels: enhancement, ready to merge
