Repository DeuxHuitHuit/framework.js-modules, pull requests merged in 2020-03, with the labels that each got.

#376 (fix) Ignore download links
  src/modules/links.js
Labels: bug

#375 (fix) Make the pattern optional
  src/com/form-field.js
Labels: bug

#363 (chore) Update to new Vimeo SDK
  src/com/oembed.js
  src/modules/oembed-vm.js
Labels: ready to merge

#249 Auto Google Maps
  src/modules/auto-google-map.js
Labels: enhancement, requested changes

#350 Changed commas for spaces
  src/modules/change-state.js
Labels: enhancement, requested changes

#386 Add option to remove hash for UpdateQsFragment
  src/modules/url-changer.js
Labels: enhancement

#381 Removed colliding code with native anchors
  src/modules/site-scroll-keeper.js
Labels: bug, ready to merge
