Repository DeuxHuitHuit/framework.js-modules, pull requests merged in 2020-01, with the labels that each got.

#349 add comment in doc - features need slide.js to work
  src/modules/auto-slide-click.js
Labels: enhancement

#343 fix error 403 and 404 - wasn't handle
  src/modules/page-load-errors.js
Labels: bug, ready to merge

#292 Callback when lottie is ready the render is done
  src/com/animation.js
Labels: bug, enhancement, ready to merge
